[Interface]
# Bouncing = 13
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = uLVNd/N+jsSMpOj8N9HQvGh1261tJo0eNtyvvO0Tq1o=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#230
PublicKey = KI9X3JvEqRpsYr3xs5q92rTus1H+oZS8/q6KVETiHCk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.182.194.227:51820

PersistentKeepalive = 25