[Interface]
# Key for Helios.conf
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = WGiS/zF43Jvs1szXoXD3EGUEfwTZphZnrkpspKe400c=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# RO-FREE#28
PublicKey = WFxt02BlKZXK8tMmgZ/q8IcnM7N8hXEhDpyaPhG3zXg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.246.130:51820

PersistentKeepalive = 25