[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 2KnAfTAjz2V1ZKZMBeZHNqNmsyTSR7/w9a9iG65tfmk=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# RO-FREE#27
PublicKey = M5oNbocDNjsEwPdPjvf0nSJbnlcRQ+yl49T5y/9rDgo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 31.14.252.2:51820

PersistentKeepalive = 25